name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          commands: |
            release
          dispatch-type: workflow
          permission: admin
          repository: yunginnanet/HellPot
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
